_:
  - &blobstore_credentials
    BLOBSTORE_WRITE_ACL:
      from_secret: blobstore_write_acl

kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: golang:1.16
    commands:
      - sed -i 's_BlobStoreDefaultUrlBase = .*_BlobStoreDefaultUrlBase = "https://blob.internal.aleemhaji.com"_' main.go
      - make test
  - name: build
    image: golang:1.16
    commands:
      - make

  - name: publish-tag
    image: golang:1.16
    commands:
      - make publish
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @publish/blob-linux-amd64 https://blob.internal.aleemhaji.com/linux-amd64/${DRONE_TAG}/blob"
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @publish/blob-darwin-amd64 https://blob.internal.aleemhaji.com/darwin-amd64/${DRONE_TAG}/blob"
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @publish/blob-darwin-arm64 https://blob.internal.aleemhaji.com/darwin-arm64/${DRONE_TAG}/blob"
    environment:
      <<: *blobstore_credentials
    when:
      event:
        - tag

  - name: publish-latest
    image: golang:1.16
    commands:
      - make publish
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @publish/blob-linux-amd64 https://blob.internal.aleemhaji.com/linux-amd64/latest/blob"
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @publish/blob-darwin-amd64 https://blob.internal.aleemhaji.com/darwin-amd64/latest/blob"
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @publish/blob-darwin-arm64 https://blob.internal.aleemhaji.com/darwin-arm64/latest/blob"
    environment:
      <<: *blobstore_credentials
    when:
      branch:
        - master

  - name: publish-internal-latest
    image: golang:1.16
    commands:
      - sed -i 's_BlobStoreDefaultUrlBase = .*_BlobStoreDefaultUrlBase = "https://blob.internal.aleemhaji.com"_' main.go
      - make publish
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @publish/blob-linux-amd64 https://blob.internal.aleemhaji.com/linux-amd64/latest-internal/blob"
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @publish/blob-darwin-amd64 https://blob.internal.aleemhaji.com/darwin-amd64/latest-internal/blob"
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @publish/blob-darwin-arm64 https://blob.internal.aleemhaji.com/darwin-arm64/latest-internal/blob"
    environment:
      <<: *blobstore_credentials
    when:
      branch:
        - master
