kind: pipeline
name: default

steps:
  - name: test
    image: golang:1.12
    commands:
      - make test
  - name: build
    image: golang:1.12
    commands:
      - make

  - name: publish-linux-amd64-version
    image: golang:1.12
    commands:
      - make
      - "curl -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @bin/blob $${BLOBSTORE_URL}/$${GOOS}-$${GOARCH}/latest/blob"
    environment:
      GOOS: linux
      GOARCH: amd64
      BLOBSTORE_URL:
        from_secret: blobstore_url
      BLOBSTORE_WRITE_ACL:
        from_secret: blobstore_write_acl
    # when:
    #   event:
    #     - tag
