_:
  - &blobstore_credentials
    BLOBSTORE_URL: 
      from_secret: blobstore_url
    BLOBSTORE_WRITE_ACL:
      from_secret: blobstore_write_acl

kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: golang:1.16
    commands:
      - make test
  - name: build
    image: golang:1.16
    commands:
      - make

  - name: publish-linux-amd64-version
    image: golang:1.16
    commands:
      - make
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @bin/blob $${BLOBSTORE_URL}/$${GOOS}-$${GOARCH}/latest/blob"
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @bin/blob $${BLOBSTORE_URL}/$${GOOS}-$${GOARCH}/${DRONE_TAG}/blob"
    environment:
      GOOS: linux
      GOARCH: amd64
      <<: *blobstore_credentials
    when:
      event:
        - tag

  - name: publish-darwin-amd64-version
    image: golang:1.16
    commands:
      - make
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @bin/blob $${BLOBSTORE_URL}/$${GOOS}-$${GOARCH}/latest/blob"
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @bin/blob $${BLOBSTORE_URL}/$${GOOS}-$${GOARCH}/${DRONE_TAG}/blob"
    environment:
      GOOS: darwin
      GOARCH: amd64
      <<: *blobstore_credentials
    when:
      event:
        - tag

  - name: publish-internal-version
    image: golang:1.16
    commands:
      - sed -i 's_BlobStoreDefaultUrlBase = .*_BlobStoreDefaultUrlBase = "http://192.168.200.71"_' src/main.go
      - make
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @bin/blob $${BLOBSTORE_URL}/$${GOOS}-$${GOARCH}/latest-internal/blob"
    environment:
      GOOS: linux
      GOARCH: amd64
      <<: *blobstore_credentials
    when:
      branch: 
        - master
