_:
  - &blobstore_credentials
    BLOBSTORE_URL: 
      from_secret: blobstore_url
    BLOBSTORE_WRITE_ACL:
      from_secret: blobstore_write_acl

kind: pipeline
type: kubernetes
name: default

steps:
  - name: test
    image: golang:1.16
    commands:
      - make test
  - name: build
    image: golang:1.16
    commands:
      - make

  - name: publish
    image: golang:1.16
    commands:
      - make publish
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @bin/blob-linux-amd64 ${BLOBSTORE_URL}/linux-amd64/latest/blob"
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @bin/blob-linux-amd64 ${BLOBSTORE_URL}/linux-amd64/${DRONE_TAG}/blob"
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @bin/blob-darwin-amd64 ${BLOBSTORE_URL}/darwin-amd64/latest/blob"
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @bin/blob-darwin-amd64 ${BLOBSTORE_URL}/darwin-amd64/${DRONE_TAG}/blob"
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @bin/blob-darwin-arm64 ${BLOBSTORE_URL}/darwin-arm64/latest/blob"
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @bin/blob-darwin-arm64 ${BLOBSTORE_URL}/darwin-arm64/${DRONE_TAG}/blob"
    environment:
      <<: *blobstore_credentials
    when:
      event:
        - tag

  - name: publish-internal-version
    image: golang:1.16
    commands:
      - sed -i 's_BlobStoreDefaultUrlBase = .*_BlobStoreDefaultUrlBase = "https://blob.internal.aleemhaji.com"_' main.go
      - make publish
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @bin/blob-linux-amd64 ${BLOBSTORE_URL}/linux-amd64/latest-internal/blob"
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @bin/blob-darwin-amd64 ${BLOBSTORE_URL}/darwin-amd64/latest-internal/blob"
      - "curl -fsSL -X POST -H \"X-Blobstore-Write-Acl: $${BLOBSTORE_WRITE_ACL}\" --data-binary @bin/blob-darwin-arm64 ${BLOBSTORE_URL}/darwin-arm64/latest-internal/blob"
    environment:
      <<: *blobstore_credentials
    when:
      branch: 
        - master
